#!/usr/bin/env python3
"""Rebuild the small COCO import ZIP using only Python's standard library.

By default, reuse the original JPEG bytes in the checked-in ZIP. To bootstrap
without that ZIP, supply --image-dir containing the two named source JPEGs.
Nothing is downloaded, decoded, resized, relabelled or generated by this script.
"""

import argparse
import hashlib
import io
import json
import zipfile
from pathlib import Path


def digest(data):
    return hashlib.sha256(data).hexdigest()


def build(directory, image_directory=None):
    provenance = json.loads((directory / "provenance.json").read_text())
    files = {}
    for name in ("annotations.json", "CREDITS.txt"):
        data = (directory / name).read_bytes()
        if digest(data) != provenance["files"][name]["sha256"]:
            raise ValueError(f"Changed source: {name}")
        files[name] = data

    source_zip = directory / "street-scenes.zip"
    for image in provenance["images"]:
        name = image["archive_path"]
        if image_directory is not None:
            data = (image_directory / Path(name).name).read_bytes()
        else:
            if not source_zip.is_file():
                raise FileNotFoundError("Use --image-dir to supply the two original JPEGs")
            with zipfile.ZipFile(source_zip) as archive:
                data = archive.read(name)
        if len(data) != image["size_bytes"] or digest(data) != image["sha256"]:
            raise ValueError(f"Changed image bytes: {name}")
        files[name] = data

    # Stored members avoid compressor-version differences. Order, timestamps and
    # file permissions are fixed; the complete sample is still under 0.5 MiB.
    output = io.BytesIO()
    order = [
        "annotations.json",
        *[image["archive_path"] for image in provenance["images"]],
        "CREDITS.txt",
    ]
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_STORED) as archive:
        for name in order:
            member = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            member.create_system = 3
            member.external_attr = 0o100644 << 16
            member.compress_type = zipfile.ZIP_STORED
            archive.writestr(member, files[name])
    return output.getvalue()


def main():
    directory = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image-dir", type=Path, help="Directory holding the two original JPEGs")
    parser.add_argument("--output", type=Path, default=directory / "street-scenes.zip")
    args = parser.parse_args()
    result = build(directory, args.image_dir)
    if args.output.exists():
        if args.output.read_bytes() != result:
            raise FileExistsError("Output already exists with different bytes; choose a new path")
    else:
        with args.output.open("xb") as target:
            target.write(result)
    print(
        json.dumps({"file": args.output.name, "size_bytes": len(result), "sha256": digest(result)})
    )


if __name__ == "__main__":
    main()
